apiVersion: v1
kind: Secret
metadata:
  name: secret-db-auth
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-elasticmail
type: Opaque
stringData:
  apiKey: '00000000-0000-0000-0000-0000000000000'
